name: 'build & push: runtime_debian_buster'
on:
  push:
    branches:
      - runtime
jobs:
  push_to_registry:
    name: 'build & push: runtime_debian_buster'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: runtime_debian_buster
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pelias/spatial
          dockerfile: runtime/runtime.debian.buster.Dockerfile
          tags: runtime_debian_buster
