name: 'build & push: runtime_ubuntu_bionic'
on:
  push:
    branches:
      - runtime
jobs:
  push_to_registry:
    name: 'build & push: runtime_ubuntu_bionic'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: runtime_ubuntu_bionic
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pelias/spatial
          dockerfile: runtime/runtime.ubuntu.bionic.Dockerfile
          tags: runtime_ubuntu_bionic
